spring:
  rabbitmq:
    password: 'secret'
    username: 'myuser'

bot:
  twitch:
    user:
      id:
    oauth:
      client-id:
      client-secret:
  subathon:
    # Expects a comma separated list of channel names to join
    channels: 
    command:
      prefix: '!'

logging:
  level:
    com:
      pronixxx:
        subathon:
          bot: trace