spring:
  rabbitmq:
    password: 'secret'
    username: 'myuser'

bot:
  twitch:
    oauth:
      token: ${TWITCH_OAUTH_TOKEN}
  subathon:
    channel: 'trizze'
    command:
      prefix: '!'

logging:
  level:
    com:
      pronixxx:
        subathon:
          bot: trace