DROP TABLE IF EXISTS `follow_event`;
DROP TABLE IF EXISTS `subscription_event`;
DROP TABLE IF EXISTS `event`;

CREATE TABLE `event` (
    id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT 'Id of the event',
    event_type ENUM('FOLLOW', 'SUBSCRIPTION') NOT NULL COMMENT 'Type of the event',
    timestamp DATETIME NOT NULL COMMENT 'Timestamp of the event',
    source VARCHAR(20) COMMENT 'Source of the event',
    username VARCHAR(30) NOT NULL COMMENT 'Username of the person causing the event',
    insert_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT 'Insertion timestamp, auto generated by database',
    PRIMARY KEY (`id`)
);

CREATE TABLE `follow_event` (
    `event_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Reference to the event',
    PRIMARY KEY (`event_id`),
    CONSTRAINT `fk_follower_event_event`
        FOREIGN KEY (`event_id`) REFERENCES `event` (`id`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION
);

CREATE TABLE `subscription_event` (
    `event_id`  BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Reference to the event',
    `sub_tier`  ENUM('PRIME', 'TIER_1', 'TIER_2', 'TIER_3') NOT NULL COMMENT 'Subscription tier',
    PRIMARY KEY (`event_id`),
    CONSTRAINT `fk_subscription_event_event`
        FOREIGN KEY (`event_id`) REFERENCES `event` (`id`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION
);