services:
  rabbitmq:
    container_name: 'rabbit-mq'
    image: 'rabbitmq:3-management'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672:5672'
      - '15672:15672'
  mariadb:
    container_name: 'maria-db-11.4'
    image: 'mariadb:11.4'
    environment:
      - 'MARIADB_ROOT_PASSWORD=password'
    ports:
      - '3306:3306'