syntax = "proto3";

package tools.subathon.grpc.configuration.v1;

option java_package = "tools.subathon.timer.proto.configuration.v1";
option java_multiple_files = true;

service ConfigurationService {
  rpc GetConfiguration(GetConfigurationRequest) returns (UserConfiguration);
  rpc PutConfiguration(UserConfiguration) returns (UserConfiguration);
}

message UserConfiguration {
  optional int64 id = 1;
  optional string channel_id = 2;
  optional int32 follower_seconds = 3;
  optional int32 raider_seconds = 4;
  optional int32 tier1_seconds = 5;
  optional int32 tier2_seconds = 6;
  optional int32 tier3_seconds = 7;
  optional int32 tier1_gift_seconds = 8;
  optional int32 tier2_gift_seconds = 9;
  optional int32 tier3_gift_seconds = 10;
  optional int32 currency_seconds = 11;
  optional int32 bits_seconds = 12;
  optional int32 initial_seconds = 13;
  optional string donation_template_pattern = 14;
  optional string donation_template_user = 15;
  optional int32 monetized_seconds_per_point = 16;
}

message GetConfigurationRequest {
  optional string channel_id = 1;
}