spring:
  rabbitmq:
    password: 'secret'
    username: 'myuser'
  datasource:
    url: ${DATASERVICE_DATASOURCE_URL}
    username: ${DATASERVICE_DATASOURCE_USERNAME}
    password: ${DATASERVICE_DATASOURCE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

logging:
  level:
    com:
      pronixxx:
        subathon: debug

server:
  port: 8081