spring:
  rabbitmq:
    password: 'secret'
    username: 'myuser'
  datasource:
    url: ${DATASERVICE_DATASOURCE_URL}
    username: ${DATASERVICE_DATASOURCE_USERNAME}
    password: ${DATASERVICE_DATASOURCE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

logging:
  level:
    com:
      pronixxx:
        subathon: debug

server:
  port: 8081

timer:
  ignoremock: true
  seconds:
    follow: 60
    raid: 3
    tier1: 300
    tier2: 600
    tier3: 1500
    tier1-gift: 300
    tier2-gift: 600
    tier3-gift: 1500
    euro: 60
    bits: 60
    initial: 172800
